# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20170628_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comedien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('actor', models.CharField(max_length=100)),
                ('films', models.ManyToManyField(to='movie.Film')),
            ],
        ),
    ]
